name: CI pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch: 

permissions:
  contents: read
  security-events: write

jobs:
# ── JOB 1 : Tests sur 3 versions Python (en parallèle) ──
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.8', '3.9', '3.10']



    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          pip install flake8

      - name: Lint with flake8
        run: |
          flake8 . --exit-zero
#          # Erreurs critiques → bloque le build
#          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
#          # Avertissements → affiché mais ne bloque pas
#          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

      - name: Test with pytest
        run: |
          pytest tests/

  # ── JOB 2 : Trivy (tourne en parallèle avec test) ──
  trivy-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@v0.36.0
        with:
          scan-type: 'fs'
          scan-ref:  '.'
          format:    'sarif'
          output:    'trivy-results.sarif'
          severity:  'CRITICAL,HIGH'


      - name: Upload results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: 'trivy-results.sarif'

